services:
  mongo:
    image: mongo:7
    container_name: healthai-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: healthai-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://mongo:27017/healthai
    depends_on:
      - mongo

  frontend:
    build: .
    container_name: healthai-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: